version: "3.8"

services:
  php-apache:
    build: .
    container_name: php_container
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html # Mount your local project files into the container
    environment:
      SUPABASE_URL: https://lkirjepcrvbzctuwdqma.supabase.co
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxraXJqZXBjcnZiemN0dXdkcW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDUzNjgsImV4cCI6MjA1NzY4MTM2OH0.ygiGNGJyL19mmp3SIKZ96ZNKgF9nS6dc4VwtsGsqKyk
    networks:
      - app_network

networks:
  app_network: