services:
  web:
    build: .
    container_name: web_container
    restart: always
    ports:
      - "8000:80"
    environment:
      SUPABASE_URL: 'https://wyicgttorbmwngjmtsnu.supabase.co'
      SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5aWNndHRvcmJtd25nam10c251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjA2NTksImV4cCI6MjA2MTIzNjY1OX0.2303RI9npdrVAQ2xLgg1Q7pLSIlDQXfxhUqdkpnmaj8'

    networks:
      - app_network

networks:
  app_network: